version: '3'

services:
  db:
    container_name: shop_db
    image: postgres
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./shop_db_init.sql:/docker-entrypoint-initdb.d/shop_db_init.sql
      - postgres_data:/var/lib/postgresql/data

  shop_back:
    container_name: shop_back
    build:
      context: ./shop_back  # Directory containing Dockerfile for backend
    env_file: ./shop_back/.env 
    depends_on:
      - db
    user: "5678:5678"
    volumes:
      - ./shop_back:/app  # Map the backend directory to the container

  shop_front:
    container_name: shop_front
    build:
      context: ./shop_front  # Directory containing Dockerfile for frontend
    env_file: ./shop_front/.env 
    volumes:
      - ./shop_front:/app  # Map the frontend directory to the container

  nginx:
    container_name: shop_nginx
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "4000:80"
    depends_on:
      - shop_back
      - shop_front

volumes:
  postgres_data:
